# Generated by Django 3.1.3 on 2020-11-10 09:57

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20201104_1736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='avatar'),
        ),
    ]
