# Generated by Django 3.1.2 on 2020-10-30 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('text', models.TextField(max_length=500, verbose_name='Содержание')),
                ('author', models.CharField(max_length=255, verbose_name='Автор')),
                ('date', models.DateTimeField(verbose_name='Дата создания')),
            ],
        ),
    ]
