# Generated by Django 3.1.2 on 2020-10-31 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0008_comment_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='date',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='date',
        ),
    ]
