# Generated by Django 3.1.2 on 2020-11-04 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0017_auto_20201103_1857'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
