# Generated by Django 3.1.2 on 2020-11-04 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0018_delete_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='image',
            field=models.ImageField(default=1, upload_to='article_images'),
            preserve_default=False,
        ),
    ]
